<Project Sdk="Aspire.AppHost.Sdk/13.5.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>5ac62599-272a-4f6f-a9d2-96345d25e52d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Services\Identity\SocietyHub.Identity.Api\SocietyHub.Identity.Api.csproj" />
    <ProjectReference Include="..\..\Gateway\SocietyHub.ApiGateway\SocietyHub.ApiGateway.csproj" />
    <ProjectReference Include="..\..\Services\Society\SocietyHub.Society.Api\SocietyHub.Society.Api.csproj" />
    <ProjectReference Include="..\..\Services\Gate\SocietyHub.Gate.Api\SocietyHub.Gate.Api.csproj" />
  </ItemGroup>

</Project>
