using FluentValidation;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SocietyHub.Gate.Api.Domain;
using SocietyHub.Gate.Api.Persistence;
using SocietyHub.SharedKernel.Abstractions;
using SocietyHub.Web.Security;
using SocietyHub.Web.Validation;

namespace SocietyHub.Gate.Api.Features;

/// <summary>
/// One movement captured while the device was offline.
///
/// <paramref name="ClientEntryId"/> is generated by the device, not the server. It is what
/// makes the sync idempotent: a tablet that uploads a batch, loses the response and retries
/// would otherwise duplicate every entry in it.
/// </summary>
public sealed record OfflineEntry(
    Guid ClientEntryId,
    DateTimeOffset OccurredAtUtc,
    EntryDirection Direction,
    Guid? FlatId,
    string? PersonName,
    string? PersonPhone,
    VisitorType? VisitorType,
    string? VehicleNumber,
    string? BadgeCode,
    bool LeftAtGate,
    string? Notes);

public sealed record SyncRequest(Guid DeviceId, IReadOnlyList<OfflineEntry> Entries);

public sealed record SyncResult(int Accepted, int AlreadyPresent, int Rejected, IReadOnlyList<string> Warnings);

public sealed class SyncValidator : AbstractValidator<SyncRequest>
{
    public SyncValidator()
    {
        RuleFor(r => r.DeviceId).NotEmpty().WithErrorCode("Device.Required");

        // Bounded so one tablet returning after a long outage cannot hold a transaction open
        // for minutes. The client pages through larger backlogs.
        RuleFor(r => r.Entries)
            .NotEmpty().WithErrorCode("Sync.Empty")
            .Must(e => e.Count <= 500).WithErrorCode("Sync.BatchTooLarge");
    }
}

/// <summary>
/// Accepts gate movements a guard device recorded while it had no network.
///
/// The gate cannot stop working because a WAN link flapped — residents are standing there and
/// couriers keep arriving. So the tablet queues locally and pushes when it reconnects, which
/// makes three things matter.
///
/// The device's own identifier is the deduplication key, because a retried upload must not
/// double every entry. The <em>capture</em> time is preserved rather than the arrival time,
/// because an incident timeline ordered by upload would be wrong precisely when it is being
/// read for evidence. And each row is flagged as an offline capture, so an investigator can
/// see why it landed hours late instead of reading the delay as suspicious.
/// </summary>
public static class OfflineSyncEndpoints
{
    public static IEndpointRouteBuilder MapSyncEndpoints(this IEndpointRouteBuilder app)
    {
        app.MapPost("/api/gate/sync", SyncAsync)
           .RequireAuthorization(SocietyHubPolicies.GateOperations)
           .WithValidation<SyncRequest>()
           .WithTags("Offline sync")
           .WithSummary("Uploads gate entries captured while the device was offline.");

        return app;
    }

    private static async Task<IResult> SyncAsync(
        SyncRequest request,
        GateDbContext context,
        ITenantContext tenant,
        ICurrentUser currentUser,
        TimeProvider timeProvider,
        ILoggerFactory loggerFactory,
        CancellationToken cancellationToken)
    {
        var logger = loggerFactory.CreateLogger("GateSync");
        var societyId = tenant.RequireSocietyId();
        var now = timeProvider.GetUtcNow();
        var guardId = currentUser.UserId;

        var warnings = new List<string>();

        var clientIds = request.Entries.Select(e => e.ClientEntryId).ToList();

        // One query for the whole batch rather than a lookup per row. A tablet returning after
        // a long outage sends hundreds, and 500 round trips inside a transaction would hold it
        // open long enough to matter at 7pm.
        var alreadyPresent = await context.GateEntries
            .Where(e => clientIds.Contains(e.Id))
            .Select(e => e.Id)
            .ToHashSetAsync(cancellationToken);

        var accepted = 0;
        var rejected = 0;

        // Badge lookups resolved in one pass for the same reason.
        var badgeCodes = request.Entries
            .Where(e => !string.IsNullOrWhiteSpace(e.BadgeCode))
            .Select(e => e.BadgeCode!)
            .Distinct()
            .ToList();

        var helpByBadge = badgeCodes.Count == 0
            ? []
            : await context.DailyHelps
                .Where(h => h.BadgeCode != null && badgeCodes.Contains(h.BadgeCode))
                .ToDictionaryAsync(h => h.BadgeCode!, h => h, cancellationToken);

        foreach (var offline in request.Entries)
        {
            if (alreadyPresent.Contains(offline.ClientEntryId))
            {
                continue;
            }

            // A timestamp from the future means the tablet's clock is wrong, and accepting it
            // would corrupt the ordering of the log for everyone. Rejected loudly rather than
            // silently clamped, because a drifting gate clock needs fixing.
            if (offline.OccurredAtUtc > now.AddMinutes(5))
            {
                rejected++;
                warnings.Add(
                    $"Entry {offline.ClientEntryId} rejected: capture time is in the future. " +
                    "Check the device clock.");
                continue;
            }

            var entry = new GateEntry(
                offline.ClientEntryId,
                societyId,
                offline.Direction,
                offline.OccurredAtUtc)
            {
                FlatId = offline.FlatId,
                PersonName = offline.PersonName,
                PersonPhone = offline.PersonPhone,
                VisitorType = offline.VisitorType,
                VehicleNumber = offline.VehicleNumber,
                LeftAtGate = offline.LeftAtGate,
                Notes = offline.Notes,
                RecordedByGuardId = guardId,
                RecordedOnDeviceId = request.DeviceId,
                WasOfflineCapture = true,
            };

            // Staff punches recorded offline still need to reach the attendance sheet, or a
            // worker loses a day's pay to a network outage.
            if (offline.BadgeCode is not null
                && helpByBadge.TryGetValue(offline.BadgeCode, out var help))
            {
                entry.DailyHelpId = help.Id;
                entry.PersonName ??= help.FullName;
                entry.VisitorType = Domain.VisitorType.Staff;
            }
            else if (offline.BadgeCode is not null)
            {
                warnings.Add(
                    $"Entry {offline.ClientEntryId}: badge '{offline.BadgeCode}' is not " +
                    "recognised. Logged as an unidentified movement.");
            }

            context.GateEntries.Add(entry);
            accepted++;
        }

        await context.SaveChangesAsync(cancellationToken);

        logger.LogInformation(
            "Gate sync from device {DeviceId}: {Accepted} accepted, {Duplicate} already present, {Rejected} rejected.",
            request.DeviceId,
            accepted,
            alreadyPresent.Count,
            rejected);

        return Microsoft.AspNetCore.Http.Results.Ok(
            new SyncResult(accepted, alreadyPresent.Count, rejected, warnings));
    }
}
