// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocietyHub.Helpdesk.Api.Persistence;

#nullable disable

namespace SocietyHub.Helpdesk.Api.Persistence.Migrations
{
    [DbContext(typeof(HelpdeskDbContext))]
    [Migration("20260827170337_InitialHelpdesk")]
    partial class InitialHelpdesk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocietyHub.Helpdesk.Api.Domain.Complaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AssignedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AssignedToName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("EscalationLevel")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("FirstResponseAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastEscalatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("RaisedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RaisedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RatingComment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Resolution")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("SatisfactionRating")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SlaDueAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SocietyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("SocietyId", "TicketNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Complaints_Ticket");

                    b.HasIndex("Status", "SlaDueAtUtc")
                        .HasDatabaseName("IX_Complaints_Sla");

                    b.HasIndex("FlatId", "Status", "RaisedAtUtc")
                        .HasDatabaseName("IX_Complaints_Flat_Status");

                    b.ToTable("Complaints", (string)null);
                });

            modelBuilder.Entity("SocietyHub.Helpdesk.Api.Domain.ComplaintAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SocietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId");

                    b.ToTable("ComplaintAttachments", (string)null);
                });

            modelBuilder.Entity("SocietyHub.Helpdesk.Api.Domain.ComplaintNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsInternalOnly")
                        .HasColumnType("bit");

                    b.Property<Guid>("SocietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Notes_Complaint");

                    b.ToTable("ComplaintNotes", (string)null);
                });

            modelBuilder.Entity("SocietyHub.Helpdesk.Api.Persistence.TicketCounter", b =>
                {
                    b.Property<Guid>("SocietyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.HasKey("SocietyId", "Year");

                    b.ToTable("TicketCounters", (string)null);
                });

            modelBuilder.Entity("SocietyHub.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SocietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventId", "ConsumerName");

                    b.HasIndex("ReceivedAtUtc");

                    b.ToTable("InboxMessages", (string)null);
                });

            modelBuilder.Entity("SocietyHub.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsPoisoned")
                        .HasColumnType("bit");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SocietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NextAttemptAtUtc", "OccurredAtUtc")
                        .HasDatabaseName("IX_OutboxMessages_Pending");

                    b.HasIndex("SocietyId", "IsPoisoned");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("SocietyHub.Helpdesk.Api.Domain.ComplaintAttachment", b =>
                {
                    b.HasOne("SocietyHub.Helpdesk.Api.Domain.Complaint", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SocietyHub.Helpdesk.Api.Domain.ComplaintNote", b =>
                {
                    b.HasOne("SocietyHub.Helpdesk.Api.Domain.Complaint", null)
                        .WithMany("Notes")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SocietyHub.Helpdesk.Api.Domain.Complaint", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
